version: 0.2
env:
  parameter-store:
    # CREATE THE PARAMETERS IN SYSTEM MANAGER IN AWS -> GOTO SYSTEM MANAGER -> PARAMETER STORE AND IN VALUE SPECIFY THE CREDENTIALS OF DOCKER HUB
    # WE ARE USING ENVIORNMENT VARIABLE FOR THE SENSITIVE INFORMATION
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r simple-python-app/requirements.txt
  build:
    commands:
       - cd simple-python-app
       - echo "Building Docker Image"
       # THIS CODE IS TO LOGIN INTO DOCKER HUB, WE ARE SPECIFYING THE CREDENTIALS
       - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
       # BUILDING AND PUSHING THE DOCKER FILE 
       - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest" .
       - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest"
  post_build:
    commands:
       - echo "Build is Successfull"

